jetstream {
    store_dir = "/data"
}

authorization {
    users = [
        {user: "api-user", password: "devpassword"},
        {user: "ingest-user", password: "devpassword"},
        {user: "worker-user", password: "devpassword"},
        {user: "realtime-user", password: "devpassword"},
        {user: "ai-user", password: "devpassword"},
        {user: "scheduler-user", password: "devpassword"}
    ]
}
