from typing import Protocol, Any, Optional, List
from types import TracebackType
from yp_api.domain.users.repository import UserRepository
from yp_api.domain.organizations.entities import Organization, OrganizationMember
from yp_api.domain.projects.entities import Project, ProjectMember
from yp_api.domain.users.entities import MagicLink
from yp_api.domain.devices.entities import Device, DeviceProfile, DeviceCredentials, Stream

class OrganizationRepository(Protocol):
    async def save(self, org: Organization) -> Organization: ...
    async def save_member(self, member: OrganizationMember) -> OrganizationMember: ...
    async def get_by_id(self, id: str) -> Optional[Organization]: ...
    async def list_for_user(self, user_id: str) -> List[Organization]: ...
    async def get_member(self, org_id: str, user_id: str) -> Optional[OrganizationMember]: ...
    async def delete(self, id: str) -> None: ...
    async def list_members(self, org_id: str) -> List[OrganizationMember]: ...
    async def count_members(self, org_id: str) -> int: ...
    async def count_owners(self, org_id: str) -> int: ...
    async def delete_member(self, org_id: str, user_id: str) -> None: ...

class ProjectRepository(Protocol):
    async def save(self, project: Project) -> Project: ...
    async def get(self, id: str) -> Optional[Project]: ...
    async def list_by_org(self, org_id: str) -> List[Project]: ...
    async def list_by_user(self, user_id: str) -> List[Project]: ...
    async def delete(self, id: str) -> None: ...
    async def count_by_org(self, org_id: str) -> int: ...
    async def check_slug_exists(self, org_id: str, slug: str) -> bool: ...

class ProjectMemberRepository(Protocol):
    async def get(self, project_id: str, user_id: str) -> Optional[ProjectMember]: ...
    async def save(self, member: ProjectMember) -> ProjectMember: ...
    async def delete(self, project_id: str, user_id: str) -> None: ...
    async def list_by_project(self, project_id: str) -> List[ProjectMember]: ...

class MagicLinkRepository(Protocol):
    async def save(self, magic_link: MagicLink) -> MagicLink: ...
    async def get_by_id(self, id: str) -> Optional[MagicLink]: ...
    async def get_by_hashed_token(self, hashed_token: str) -> Optional[MagicLink]: ...
    async def get_latest_for_email(self, email: str, purpose: str) -> Optional[MagicLink]: ...

class RefreshTokenRepository(Protocol):
    async def save(self, refresh_token: Any) -> Any: ...
    async def get_by_id(self, id: str) -> Optional[Any]: ...
    async def get_by_hashed_token(self, hashed_token: str) -> Optional[Any]: ...
    async def revoke_all_for_user(self, user_id: str) -> None: ...
    async def get_active_by_user(self, user_id: str) -> List[Any]: ...
    async def get_by_id_and_user(self, id: str, user_id: str) -> Optional[Any]: ...

from yp_api.domain.organizations.entities import OrganizationInvite
from yp_api.domain.audit.entities import AuditEvent

class OrganizationInviteRepository(Protocol):
    async def save(self, invite: OrganizationInvite) -> OrganizationInvite: ...
    async def get_by_id(self, id: str) -> Optional[OrganizationInvite]: ...
    async def get_by_hashed_token(self, hashed_token: str) -> Optional[OrganizationInvite]: ...
    async def list_by_org(self, org_id: str) -> List[OrganizationInvite]: ...
    async def delete(self, id: str) -> None: ...

class AuditRepository(Protocol):
    async def save(self, event: AuditEvent) -> AuditEvent: ...

class DeviceProfileRepository(Protocol):
    async def save(self, profile: DeviceProfile) -> DeviceProfile: ...
    async def get(self, id: str) -> Optional[DeviceProfile]: ...
    async def list_by_project(self, project_id: str) -> List[DeviceProfile]: ...
    async def delete(self, id: str) -> None: ...
    async def count_by_project(self, project_id: str) -> int: ...

class DeviceRepository(Protocol):
    async def save(self, device: Device) -> Device: ...
    async def get(self, id: str) -> Optional[Device]: ...
    async def list_by_project(self, project_id: str, status: Optional[str] = None) -> List[Device]: ...
    async def delete(self, id: str) -> None: ...
    async def count_by_project(self, project_id: str) -> int: ...
    async def count_by_org(self, org_id: str) -> int: ...
    async def save_credentials(self, creds: DeviceCredentials) -> DeviceCredentials: ...
    async def get_credentials(self, device_id: str) -> Optional[DeviceCredentials]: ...
    async def count_by_profile(self, profile_id: str) -> int: ...

class StreamRepository(Protocol):
    async def save(self, stream: Stream) -> Stream: ...
    async def get(self, id: str) -> Optional[Stream]: ...
    async def get_by_key(self, device_id: str, key: str) -> Optional[Stream]: ...
    async def list_by_device(self, device_id: str) -> List[Stream]: ...
    async def list_by_project(self, project_id: str) -> List[Stream]: ...

from yp_api.domain.automation.entities import Rule, Webhook, RuleRepository, WebhookRepository
from yp_api.domain.fleets.entities import FleetRepository, FirmwareRepository

from yp_api.domain.dashboards.entities import Dashboard

class DashboardRepository(Protocol):
    async def save(self, dashboard: Dashboard) -> Dashboard: ...
    async def get(self, id: str) -> Optional[Dashboard]: ...
    async def list_by_project(self, project_id: str) -> List[Dashboard]: ...
    async def delete(self, id: str) -> None: ...

class UnitOfWork(Protocol):
    users: UserRepository
    organizations: OrganizationRepository
    projects: ProjectRepository
    project_members: ProjectMemberRepository
    magic_links: MagicLinkRepository
    refresh_tokens: RefreshTokenRepository
    organization_invites: OrganizationInviteRepository
    audit_events: AuditRepository
    devices: DeviceRepository
    device_profiles: DeviceProfileRepository
    streams: StreamRepository
    dashboards: DashboardRepository
    rules: RuleRepository
    webhooks: WebhookRepository
    fleets: FleetRepository
    firmwares: FirmwareRepository

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
